default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: f8ysz789
  host: localhost

development:
  <<: *default
  database: afisha_development

test:
  <<: *default
  database: afisha_test

production:
  <<: *default
  database: afisha_production
  username: postgres
  password: f8ysz789
